import { Apartment, Post } from "./interfaces";

export const MOCK_APARTMENT_LIST: Apartment[] = [
  {
    id: 'U101',
    unitNumber: '101',
    residentName: 'Alice Johnson',
    status: 'Occupied',
    type: 'Owner',
    walletBalance: 15500.50, // Wallet balance for easy reference
  },
  {
    id: 'U102',
    unitNumber: '102',
    residentName: 'Babatunde Adekunle',
    status: 'Occupied',
    type: 'Tenant',
    walletBalance: 5000.00,
  },
  {
    id: 'U201',
    unitNumber: '201',
    residentName: 'Vacant',
    status: 'Vacant',
    type: 'Owner', // Owner's unit, but currently vacant
    walletBalance: 0.00,
  },
  {
    id: 'U205',
    unitNumber: '205',
    residentName: 'Chioma Okoro',
    status: 'Occupied',
    type: 'Tenant',
    walletBalance: 45200.75,
  },
  {
    id: 'U302',
    unitNumber: '302',
    residentName: 'Estate Management',
    status: 'Under Maintenance',
    type: 'Owner',
    walletBalance: 0.00,
  },
  {
    id: 'U401',
    unitNumber: '401',
    residentName: 'David Lee',
    status: 'Occupied',
    type: 'Owner',
    walletBalance: 8750.00,
  },
];

export const MOCK_POSTS: Post[] = [
  {
    id: "1",
    author_name: "Alice Freeman",
    author_role: "resident",
    title: "Suspicious car parked near Gate B",
    content:
      "Has anyone seen a red sedan parked near Gate B for the last 3 days?",
    category: "Alerts",
    likes_count: 12,
    comments: [
      {
        id: "c1",
        author: "Security Desk",
        authorRole: "admin",
        content: "Towing service has been called.",
        timestamp: "1 hour ago",
      },
    ],
    timestamp: "2 hours ago",
  },
  {
    id: "2",
    author: "Mark Wilson",
    authorRole: "resident",
    title: "Selling unused Gym Equipment",
    content: "I am selling a treadmill and some dumbbells. DM for prices.",
    category: "Marketplace",
    likes: 4,
    comments: [],
    timestamp: "5 hours ago",
  },
  {
    id: "3",
    author: "Estate Admin",
    authorRole: "admin",
    title: "Water tank cleaning schedule",
    content: "Water tank cleaning will happen on Tuesday from 10 AM to 4 PM.",
    category: "General",
    likes: 45,
    comments: [],
    timestamp: "1 day ago",
  },
  // --- ALERTS ---
  {
    id: "4",
    author: "Chief Security",
    authorRole: "superadmin",
    title: "Routine Patrol Update",
    content: "We are increasing night patrols around the West Wing due to recent streetlight outages. Please stay vigilant.",
    category: "Alerts",
    likes: 28,
    comments: [],
    timestamp: "30 mins ago",
  },
  {
    id: "5",
    author: "David Okon",
    authorRole: "resident",
    title: "Lost Golden Retriever",
    content: "My dog 'Goldie' slipped out of the gate this morning. She’s wearing a blue collar. Please call if seen!",
    category: "Alerts",
    likes: 56,
    comments: [{ id: "c2", author: "Alice Freeman", content: "I think I saw her near the park!", timestamp: "5 mins ago" }],
    timestamp: "2 hours ago",
  },
  {
    id: "6",
    author: "Estate Admin",
    authorRole: "admin",
    title: "Fire Drill Scheduled",
    content: "There will be a mandatory fire safety drill this Saturday at 10 AM. Please follow the evacuation signs.",
    category: "Alerts",
    likes: 15,
    comments: [],
    timestamp: "4 hours ago",
  },
  {
    id: "7",
    author: "Security Gate A",
    authorRole: "admin",
    title: "Delivery Truck Blockage",
    content: "A large truck is currently blocking the main entrance at Gate A. Please use Gate B for the next hour.",
    category: "Alerts",
    likes: 9,
    comments: [],
    timestamp: "10 mins ago",
  },

  // --- MARKETPLACE ---
  {
    id: "8",
    author: "Sarah James",
    authorRole: "resident",
    title: "Home-made Jollof Rice",
    content: "Taking orders for weekend party packs! Authentic smoky flavor. Send a DM to pre-order yours.",
    category: "Marketplace",
    likes: 34,
    comments: [],
    timestamp: "1 hour ago",
  },
  {
    id: "9",
    author: "Michael Chen",
    authorRole: "resident",
    title: "Used Toyota Camry for Sale",
    content: "2018 Model, clean interior, low mileage. Looking for a quick sale. Inspect at House 24B.",
    category: "Marketplace",
    likes: 12,
    comments: [],
    timestamp: "3 hours ago",
  },
  {
    id: "10",
    author: "Estate Laundry",
    authorRole: "resident",
    title: "Dry Cleaning Discount",
    content: "Get 20% off all duvet and curtain cleaning this week only! Pick up and delivery available within the estate.",
    category: "Marketplace",
    likes: 21,
    comments: [],
    timestamp: "5 hours ago",
  },
  {
    id: "11",
    author: "Emeka Obi",
    authorRole: "resident",
    title: "Free Moving Boxes",
    content: "Just moved in and have about 20 sturdy boxes to give away. Come pick them up at Block C.",
    category: "Marketplace",
    likes: 7,
    comments: [],
    timestamp: "6 hours ago",
  },

  // --- GENERAL ---
  {
    id: "12",
    author: "Estate Management",
    authorRole: "superadmin",
    title: "New Playground Equipment",
    content: "We are excited to announce that new swings and slides have been installed in the community park!",
    category: "General",
    likes: 89,
    comments: [],
    timestamp: "1 day ago",
  },
  {
    id: "13",
    author: "Tunde Bakare",
    authorRole: "resident",
    title: "Football Match this Sunday",
    content: "The Residents FC is looking for more players for our weekly friendly match at the estate pitch. 4 PM kick-off!",
    category: "General",
    likes: 42,
    comments: [{ id: "c3", author: "Mark Wilson", content: "Count me in!", timestamp: "1 hour ago" }],
    timestamp: "Yesterday",
  },
  {
    id: "14",
    author: "Admin Office",
    authorRole: "admin",
    title: "Electricity Meter Maintenance",
    content: "Our technicians will be going round to check prepaid meters starting Monday. Ensure someone is home.",
    category: "General",
    likes: 18,
    comments: [],
    timestamp: "2 days ago",
  },
  {
    id: "15",
    author: "Grace Ade",
    authorRole: "resident",
    title: "Book Club Meeting",
    content: "We're meeting at the clubhouse this Friday to discuss 'Things Fall Apart'. All residents are welcome!",
    category: "General",
    likes: 15,
    comments: [],
    timestamp: "3 hours ago",
  },
];
